.travis.yml
README.md
pom.xml
sonar-project.properties

Integrated new tools:
- SonarQube (code quality)
- Snyk (dependency vulnerabilities)
- LGTM (zero-days and other critical bugs)
Added badges to README.md

ci: additional tools

---

README.md

added missing badges to README.md

feat: added lgtm badges

---

pom.xml
src/main/java/io/github/janmalch/kino/api/boundary/PingResource.java
src/main/resources/META-INF/logback.xml

added logging functionality
added missing JEE dependencies

feat: added logging functionality

---

src/main/java/io/github/janmalch/kino/api/APIExceptionMapper.java
src/main/java/io/github/janmalch/kino/api/Responsify.java
src/main/java/io/github/janmalch/kino/problem/Problem.java
src/main/java/io/github/janmalch/kino/problem/ProblemBuilder.java
src/main/java/io/github/janmalch/kino/problem/ProblemImpl.java
src/main/java/io/github/janmalch/kino/problem/ProblemTemplate.java
src/main/java/io/github/janmalch/kino/problem/ProblemTemplateImpl.java
src/test/java/io/github/janmalch/kino/problem/ProblemBuilderTests.java
src/test/java/io/github/janmalch/kino/problem/ProblemTemplateImplTests.java
src/test/java/io/github/janmalch/kino/problem/ProblemTests.java

Added class for problem templates to simplify problem creation in controls

feat: problem template

---

src/main/java/io/github/janmalch/kino/api/APIExceptionMapper.java
src/main/java/io/github/janmalch/kino/control/SignUpControl.java
src/main/java/io/github/janmalch/kino/control/validation/SignUpDtoValidator.java
src/main/java/io/github/janmalch/kino/repository/Repository.java
src/main/java/io/github/janmalch/kino/util/Contract.java
src/main/java/io/github/janmalch/kino/util/Mapper.java

Minor style improvements
Fixed birthday format bug

style: codestyle

---

src/main/java/io/github/janmalch/kino/entity/Account.java
src/main/java/io/github/janmalch/kino/entity/Role.java
src/test/java/io/github/janmalch/kino/entity/RoleTest.java

Rollensystem für Accounts implementiert

feat: roles

---

src/main/java/io/github/janmalch/kino/api/boundary/MovieResource.java
src/main/java/io/github/janmalch/kino/api/model/MovieDto.java
src/main/java/io/github/janmalch/kino/control/GetMovieControl.java
src/main/java/io/github/janmalch/kino/control/NewMovieControl.java
src/main/java/io/github/janmalch/kino/control/RemoveMovieControl.java
src/main/java/io/github/janmalch/kino/control/UpdateMovieControl.java
src/main/java/io/github/janmalch/kino/repository/MovieRepository.java
src/main/java/io/github/janmalch/kino/repository/Repository.java
src/main/java/io/github/janmalch/kino/repository/TransactionProvider.java
src/main/java/io/github/janmalch/kino/repository/UserRepository.java
src/main/java/io/github/janmalch/kino/repository/VoidConsumer.java
src/test/java/io/github/janmalch/kino/api/boundary/MovieResourceTest.java
src/test/java/io/github/janmalch/kino/control/GetMovieControlTest.java
src/test/java/io/github/janmalch/kino/control/NewMovieControlTest.java
src/test/java/io/github/janmalch/kino/control/NewMovieMapperTest.java
src/test/java/io/github/janmalch/kino/control/RemoveMovieControlTest.java
src/test/java/io/github/janmalch/kino/control/UpdateMovieControlTest.java
src/test/java/io/github/janmalch/kino/control/UpdateMovieMapperTest.java
src/test/java/io/github/janmalch/kino/repository/RepositoryTest.java

Added basic use-cases to
- Create a new movie
- Read a single movie by ID
- Delete a single movie by ID
- Update a single movie by ID

feat: movie crud

---

src/main/java/io/github/janmalch/kino/api/APIExceptionMapper.java
src/main/java/io/github/janmalch/kino/problem/Problem.java
src/main/java/io/github/janmalch/kino/problem/Problems.java
src/main/java/io/github/janmalch/kino/problem/ThrowableProblem.java
src/test/java/io/github/janmalch/kino/api/APIExceptionMapperTest.java
src/test/java/io/github/janmalch/kino/problem/ProblemsTest.java
src/test/java/io/github/janmalch/kino/problem/ThrowableProblemTest.java

Adds utility functions for common validations / problems
Minor improvement in Problem builder with given Status types
---
Closes #42

feat: problems

---

src/main/java/io/github/janmalch/kino/control/account/GetAccountByIdControl.java
src/main/java/io/github/janmalch/kino/control/account/GetAllAccountsControl.java
src/main/java/io/github/janmalch/kino/control/account/SignUpControl.java
src/main/java/io/github/janmalch/kino/control/generic/DeleteEntityControl.java
src/main/java/io/github/janmalch/kino/control/generic/GetEntitiesControl.java
src/main/java/io/github/janmalch/kino/control/generic/GetEntityControl.java
src/main/java/io/github/janmalch/kino/control/generic/NewEntityControl.java
src/main/java/io/github/janmalch/kino/control/generic/UpdateEntityControl.java
src/main/java/io/github/janmalch/kino/entity/Account.java
src/main/java/io/github/janmalch/kino/entity/CinemaHall.java
src/main/java/io/github/janmalch/kino/entity/Identifiable.java
src/main/java/io/github/janmalch/kino/entity/Movie.java
src/main/java/io/github/janmalch/kino/entity/Presentation.java
src/main/java/io/github/janmalch/kino/entity/PriceCategory.java
src/main/java/io/github/janmalch/kino/entity/Reservation.java
src/main/java/io/github/janmalch/kino/entity/Seat.java
src/main/java/io/github/janmalch/kino/util/Mapper.java
src/main/java/io/github/janmalch/kino/util/Mapping.java
src/test/java/io/github/janmalch/kino/control/generic/GenericEntityControlTest.java
src/test/java/io/github/janmalch/kino/util/ReflectionMapperTest.java

Adds generic controls for CRUD use cases

feat: generic controls

---

pom.xml
src/main/java/io/github/janmalch/kino/api/ValidationExceptionMapper.java
src/main/java/io/github/janmalch/kino/api/WebApplication.java
src/main/java/io/github/janmalch/kino/api/boundary/PriceCategoryResource.java
src/main/java/io/github/janmalch/kino/api/model/MovieDto.java
src/main/java/io/github/janmalch/kino/api/model/PresentationDto.java
src/main/java/io/github/janmalch/kino/api/model/PriceCategoryBaseDto.java
src/main/java/io/github/janmalch/kino/api/model/PriceCategoryDto.java

UseCases: Guest
Introduces input validation
---
Closes #30

feat: movie infos

---

src/main/java/io/github/janmalch/kino/control/ResultBuilder.java
src/main/java/io/github/janmalch/kino/control/account/DeleteAccountByIdControl.java
src/main/java/io/github/janmalch/kino/control/account/SignUpControl.java
src/main/java/io/github/janmalch/kino/control/movie/RemoveMovieControl.java
src/main/java/io/github/janmalch/kino/control/reservation/DeleteMyReservationByIdControl.java
src/main/java/io/github/janmalch/kino/control/reservation/DeleteReservationByIdControl.java
src/test/java/io/github/janmalch/kino/control/account/DeleteAccountByIdControlTest.java
src/test/java/io/github/janmalch/kino/control/movie/RemoveMovieControlTest.java

revert: remove Success - clean up

---

src/main/java/io/github/janmalch/kino/api/boundary/ReservationResource.java
src/main/resources/drop-and-create.sql
src/main/resources/dummy-movies.sql
src/main/resources/user.sql

Some SQL scripts to create dummy data

feat: sql scripts

---

src/main/angular/kino-frontend/src/app/api/api.module.ts
src/main/angular/kino-frontend/src/app/api/api/api.ts
src/main/angular/kino-frontend/src/app/api/api/default.service.ts
src/main/angular/kino-frontend/src/app/api/encoder.ts
src/main/angular/kino-frontend/src/app/api/model/cinemaHallDto.ts
src/main/angular/kino-frontend/src/app/api/model/movieDto.ts
src/main/angular/kino-frontend/src/app/api/model/movieOverviewDto.ts
src/main/angular/kino-frontend/src/app/api/model/presentationWithSeatsDto.ts
src/main/angular/kino-frontend/src/app/api/model/reservationInfoDto.ts
src/main/angular/kino-frontend/src/app/api/variables.ts
src/main/java/io/github/janmalch/kino/api/boundary/MyAccountResource.java

removed api path in control
refactor api path on angular

fix:myaccount

---

src/main/angular/kino-frontend/src/app/core/auth/auth.service.ts

save token in SessionStorage to prevent log out on simple refresh
---
Closes #77

feat: save token in SessionStorage

---

src/main/angular/kino-frontend/src/app/core/core.module.ts
src/main/angular/kino-frontend/src/environments/environment.prod.ts
src/main/angular/kino-frontend/src/environments/environment.ts

Make API depend on environment (dev / prod)

fix: API path depends on environment

---

sql-scripts/01_drop-and-create.sql
sql-scripts/03_dummy-movies.sql
src/main/angular/kino-frontend/src/app/admin/routes/movies/movies.component.ts
src/main/angular/kino-frontend/src/app/api/model/movieDto.ts
src/main/angular/kino-frontend/src/app/api/model/movieInfoDto.ts
src/main/angular/kino-frontend/src/app/api/model/newMovieDto.ts
src/main/angular/kino-frontend/src/app/core/services/movie.service.ts
src/main/angular/kino-frontend/src/app/shared/components/movie-all-infos-card/movie-all-infos-card.component.html
src/main/angular/kino-frontend/src/app/shared/components/movie-all-infos-card/movie-all-infos-card.component.ts
src/main/angular/kino-frontend/src/app/shared/components/movie-card/movie-card.component.html
src/main/angular/kino-frontend/src/app/shared/components/movie-card/movie-card.component.scss
src/main/java/io/github/janmalch/kino/api/model/movie/MovieDto.java
src/main/java/io/github/janmalch/kino/api/model/movie/MovieInfoDto.java
src/main/java/io/github/janmalch/kino/api/model/movie/NewMovieDto.java
src/main/java/io/github/janmalch/kino/control/movie/MovieDtoMapper.java
src/main/java/io/github/janmalch/kino/control/movie/NewMovieControl.java
src/main/java/io/github/janmalch/kino/control/movie/UpdateMovieControl.java
src/main/java/io/github/janmalch/kino/entity/Movie.java
src/test/java/io/github/janmalch/kino/api/boundary/MovieResourceTest.java
src/test/java/io/github/janmalch/kino/control/movie/NewMovieControlTest.java

add Image URL in DTO and Entity to get URL String for Images

feat:movie image url

---

src/main/angular/kino-frontend/src/app/core/services/reservation.service.ts
src/main/angular/kino-frontend/src/app/reservation/all-my-reservations/all-my-reservations.component.ts
src/main/angular/kino-frontend/src/app/reservation/reservations-list/reservations-list.component.html
src/main/angular/kino-frontend/src/app/reservation/reservations-list/reservations-list.component.ts

fix: partition my reservations in frontend properly

---

src/main/angular/kino-frontend/src/app/core/interceptors/error.interceptor.ts

fix: show instance information in snackbar to track error

---

src/main/angular/kino-frontend/src/app/core/auth/auth.interceptor.ts
src/main/angular/kino-frontend/src/app/core/auth/auth.service.ts
src/main/angular/kino-frontend/src/app/core/auth/session-storage-subject.rxjs.ts
src/main/angular/kino-frontend/src/app/reservation/reservation-permission.guard.spec.ts
src/main/angular/kino-frontend/src/app/reservation/reservation-permission.guard.ts
src/main/angular/kino-frontend/src/app/reservation/reservation-routing.module.ts

Fixes some authentication issues in the frontend

fix: issue104

---

src/main/java/io/github/janmalch/kino/api/boundary/MyAccountResource.java
src/test/java/io/github/janmalch/kino/api/boundary/MyAccountResourceTest.java

Return TokenDto instead of Token to match API description

fix: return TokenDto from editMyAccount

---

src/main/java/io/github/janmalch/kino/api/WebApplication.java

add all register Resources
closes #101

fix: add resources to register all

---

src/main/angular/kino-frontend/src/app/admin/components/generic-form/generic-form.component.ts
src/main/angular/kino-frontend/src/app/admin/routes/movies/movies.component.ts
src/main/angular/kino-frontend/src/app/admin/routes/presentation/presentation.component.ts

Fixes date parsing issues in administration
---
Closes #97

fix: date parsing

---

src/main/java/io/github/janmalch/kino/api/boundary/PresentationResource.java

fix: User not authorized Exception when accessing it

---

sql-scripts/03_dummy-movies.sql
src/main/angular/kino-frontend/src/app/admin/routes/movies/movies.component.ts
src/main/angular/kino-frontend/src/app/api/model/movieDto.ts
src/main/angular/kino-frontend/src/app/api/model/movieInfoDto.ts
src/main/angular/kino-frontend/src/app/api/model/newMovieDto.ts
src/main/angular/kino-frontend/src/app/movie/movie-overview/movie-overview.component.html
src/main/angular/kino-frontend/src/app/movie/movie.module.ts
src/main/angular/kino-frontend/src/app/movie/pipes/filter-past.pipe.spec.ts
src/main/angular/kino-frontend/src/app/movie/pipes/filter-past.pipe.ts
src/main/angular/kino-frontend/src/app/movie/pipes/index.ts
src/main/angular/kino-frontend/src/app/movie/running-movies/running-movies.component.html
src/main/angular/kino-frontend/src/app/movie/running-movies/running-movies.component.ts
src/main/angular/kino-frontend/src/styles.scss
src/main/java/io/github/janmalch/kino/api/model/movie/MovieDto.java
src/main/java/io/github/janmalch/kino/api/model/movie/MovieInfoDto.java
src/main/java/io/github/janmalch/kino/api/model/movie/NewMovieDto.java
src/main/java/io/github/janmalch/kino/control/movie/GetCurrentMoviesControl.java
src/main/java/io/github/janmalch/kino/control/movie/MovieDtoMapper.java
src/main/java/io/github/janmalch/kino/control/movie/NewMovieControl.java
src/main/java/io/github/janmalch/kino/control/movie/UpdateMovieControl.java
src/main/java/io/github/janmalch/kino/entity/Movie.java
src/main/java/io/github/janmalch/kino/repository/specification/CurrentMoviesSpec.java
src/test/java/io/github/janmalch/kino/api/boundary/MovieResourceTest.java
src/test/java/io/github/janmalch/kino/control/movie/NewMovieControlTest.java
src/test/java/io/github/janmalch/kino/control/movie/NewMovieMapperTest.java
src/test/java/io/github/janmalch/kino/control/movie/UpdateMovieMapperTest.java

Fixes issues with the movie overview
Removes date fields from movies
administration updated accordingly
Frontend does not show presentations from the past anymore
---
Closes #93

fix: issue93

---

src/main/java/io/github/janmalch/kino/control/ManagingControl.java
src/main/java/io/github/janmalch/kino/security/AuthorizationFilter.java
src/main/java/io/github/janmalch/kino/security/TokenSecurityContext.java

Ensure closing repositories on exceptions. All repositories usages should now always get closed
---
Closes #109

feat: ensure closing repositories in finally block

---

src/main/angular/kino-frontend/src/app/core/services/reservation.service.ts
src/main/angular/kino-frontend/src/app/reservation/new-reservation/new-reservation.component.ts

fix: clear cache after making a new reservation

---

src/main/java/io/github/janmalch/kino/repository/RepositoryImpl.java

fix: close EntityManagerFactory aswell

---

src/main/angular/kino-frontend/src/app/core/auth/auth.service.ts

fix: clear user cache on logout

---

sql-scripts/03_dummy-movies.sql
sql-scripts/04_dummy_reservation.sql

closes #106
added cinehall/seats/movies/presentation
added reservation+reservationWithSeats

feat:issue106

---

src/test/java/io/github/janmalch/kino/api/boundary/PresentationResourceTest.java

closes #125 
kam kein Flickering sondern immer ein failed. Aber geht wieder

fix: add beforeEach DB teardown

---

src/main/angular/kino-frontend/src/app/core/core.module.ts
src/main/angular/kino-frontend/src/app/core/interceptors/error.interceptor.ts
src/main/angular/kino-frontend/src/app/core/interceptors/index.ts
src/main/angular/kino-frontend/src/app/core/interceptors/session-timeout.interceptor.ts
src/main/angular/kino-frontend/src/app/core/interceptors/token.interceptor.ts
src/main/angular/kino-frontend/src/app/login/login/login.component.ts
src/main/java/io/github/janmalch/kino/api/WebApplication.java
src/main/java/io/github/janmalch/kino/security/RefreshTokenResponseFilter.java

Extended manual testing required before merging
---
Closes #124

fix: issue124

---

src/main/angular/kino-frontend/src/app/login/register/register.component.html

feat: show birthday format indicator

---

src/main/angular/kino-frontend/src/app/core/services/movie.service.ts

style: remove console.log call

---

src/main/angular/kino-frontend/src/app/admin/components/generic-overview/generic-overview.component.html

refactor: change description in admin overview

---

src/main/angular/kino-frontend/src/app/login/login/login.component.html

feat: add hint for quick login buttons

---

src/main/angular/kino-frontend/src/app/admin/routes/movies/movies.component.html

- remove non-existing dates on movie admin
- replace with ageRating
---
Closes #122

feat: remove non-existing dates on movie admin

---

src/main/angular/kino-frontend/src/app/admin/components/generic-overview/generic-overview.component.html
src/main/angular/kino-frontend/src/app/admin/components/generic-overview/generic-overview.component.ts
src/main/angular/kino-frontend/src/app/admin/routes/reservations/reservations.component.html
src/main/angular/kino-frontend/src/app/admin/routes/reservations/reservations.component.scss
src/main/angular/kino-frontend/src/app/admin/routes/reservations/reservations.component.ts
src/main/angular/kino-frontend/src/app/reservation/reservation.module.ts

[Preview](https://github.com/JanMalch/kino/issues/100#issuecomment-504166162)
---
Closes #100

feat: show seats in reservation admin view

---

src/main/java/io/github/janmalch/kino/api/boundary/ReservationResource.java

feat:add demo branch

---

src/main/java/io/github/janmalch/kino/api/model/auth/LoginDto.java
src/main/java/io/github/janmalch/kino/api/model/movie/NewMovieDto.java
src/main/java/io/github/janmalch/kino/entity/CinemaHall.java
src/main/java/io/github/janmalch/kino/entity/Movie.java
src/main/java/io/github/janmalch/kino/entity/Presentation.java

closes #22 
add orphan removal of deleting entities

feat:issue22

---

src/main/java/io/github/janmalch/kino/api/model/auth/LoginDto.java
src/main/java/io/github/janmalch/kino/api/model/movie/NewMovieDto.java

add dto constraints
closes #49

feat:issue49
